### PR TITLE
🐛 add missing event argument to handle_touch()

### PR DESCRIPTION
**Pull request by larpon**
This PR fixes building with current master

### CODE REVIEW

**Comment by ali-furkan** [comment]
I forgot commit that argument error at local repo 😁. Thanks for your contribution.

**Comment by rcqls** [comment]
Already proposed in my PR 😁in combination with some usual issue with gg.scale required at least for retina screen of my MacBook.

**Comment by larpon** [comment]
> Already proposed in my PR 😁in combination with some usual issue with gg.scale required at least for retina screen of my MacBook.

Aw snap! I didn't see that 😄
We're over it like lions, lol

**Comment by rcqls** [comment]
> Aw snap! I didn't see that 😄 We're over it like lions, lol

 😂

**Pull request merged**
