### PR TITLE
Fixed compile errors V 0.3.1

### PR DESCRIPTION
**Pull request by rhighs**
Handle option and remove mathutil.min as it is deprecated now.

### CODE REVIEW

**Comment by ali-furkan** [comment]
I knew the game will have errors in the new version of V but I forgot it 😄. Thanks for pr.

**Comment by ali-furkan** [comment]
I guess it still has problems that some gg's methods are deprecated and etc. . It would be better to merge it after fixing problems

**Comment by rhighs** [comment]
How's that? it ran just fine on my machine :/

**Comment by ali-furkan** [comment]
It's working well but has the warnings that i said above.
image

**Comment by rhighs** [comment]
Ok then, I can fix it when I'll have some spare time

**Pull request merged**
